/**
 * PostgreSQL database migration script.
 * Usage: npm run migrate
 */

import { closePool, getPool } from './db';
import { logger } from '../services/logger';

const DDL_STATEMENTS = [
  `CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wa_jid VARCHAR(64) UNIQUE NOT NULL,
    display_name VARCHAR(255),
    first_seen TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMPTZ,
    memory_opt_out BOOLEAN NOT NULL DEFAULT FALSE
  )`,

  `CREATE TABLE IF NOT EXISTS groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wa_group_id VARCHAR(64) UNIQUE NOT NULL,
    name VARCHAR(255),
    personality VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,

  `CREATE TABLE IF NOT EXISTS group_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL DEFAULT 'member' CHECK (role IN ('member', 'admin')),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (group_id, user_id)
  )`,

  `CREATE TABLE IF NOT EXISTS admin_actions_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    actor_user_id INTEGER NOT NULL REFERENCES users(id),
    target_user_id INTEGER REFERENCES users(id),
    action_type VARCHAR(16) NOT NULL CHECK (action_type IN ('kick', 'promote', 'demote', 'tagall')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,

  `CREATE TABLE IF NOT EXISTS command_usage_log (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER REFERENCES groups(id) ON DELETE SET NULL,
    user_id INTEGER NOT NULL REFERENCES users(id),
    command VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,

  `CREATE TABLE IF NOT EXISTS rate_limits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    command VARCHAR(64) NOT NULL,
    last_used_at TIMESTAMPTZ NOT NULL,
    UNIQUE (group_id, command)
  )`,

  `CREATE TABLE IF NOT EXISTS user_rate_limits (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    action VARCHAR(64) NOT NULL,
    window_started_at TIMESTAMPTZ NOT NULL,
    usage_count INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id, action)
  )`,

  `CREATE TABLE IF NOT EXISTS ai_memory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
    role VARCHAR(16) NOT NULL CHECK (role IN ('user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,

  `CREATE TABLE IF NOT EXISTS media_jobs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    job_type VARCHAR(32) NOT NULL CHECK (
      job_type IN ('sticker_to_image', 'image_to_sticker', 'gif_to_video', 'video_to_gif')
    ),
    status VARCHAR(16) NOT NULL DEFAULT 'pending' CHECK (
      status IN ('pending', 'processing', 'done', 'failed')
    ),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
];

const SCHEMA_UPDATE_STATEMENTS = [
  `ALTER TABLE groups ADD COLUMN IF NOT EXISTS personality VARCHAR(500)`,
  `ALTER TABLE ai_memory ALTER COLUMN content TYPE TEXT`,
];

const INDEX_STATEMENTS = [
  `CREATE INDEX IF NOT EXISTS idx_ai_memory_user ON ai_memory(user_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_ai_memory_user_group ON ai_memory(user_id, group_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_command_log_group ON command_usage_log(group_id, created_at)`,
];

export async function migrate(): Promise<void> {
  const pool = getPool();
  const client = await pool.connect();
  logger.info('Starting PostgreSQL database migration...');

  try {
    await client.query('BEGIN');
    for (const sql of DDL_STATEMENTS) {
      const tableName = sql.match(/CREATE TABLE IF NOT EXISTS\s+(\w+)/)?.[1] || 'unknown';
      await client.query(sql);
      logger.info(`Table ${tableName} ready`);
    }
    for (const sql of SCHEMA_UPDATE_STATEMENTS) await client.query(sql);
    for (const sql of INDEX_STATEMENTS) await client.query(sql);
    await client.query('COMMIT');
    logger.info('PostgreSQL database migration complete!');
  } catch (err) {
    await client.query('ROLLBACK');
    throw err;
  } finally {
    client.release();
    await closePool();
  }
}

if (require.main === module) {
  migrate().catch((err) => {
    logger.error({ err }, 'Migration failed');
    process.exitCode = 1;
  });
}
